[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "dataset-archiver"
dynamic = ["version"]
description = "Upload dataset folder to WebDAV and attach metadata."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache-2.0"}
authors = [{name = "Andrea Munafo", email = "andrea.munafo@gmail.com"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = []

[project.urls]
Repository = "https://github.com/Robotics-Research-Lab/dataset-archiver"
Documentation = "https://Robotics-Research-Lab.github.io/dataset-archiver"

[project.entry-points.nbdev]
dataset_archiver = "dataset_archiver._modidx:d"


[project.scripts]
upload-dataset = "dataset_archiver.cli:main"

[tool.setuptools.dynamic]
version = {attr = "dataset_archiver.__version__"}

[tool.setuptools.packages.find]
include = ["dataset_archiver"]

[tool.nbdev]
